/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock */
        post: operations["unlock_api_v1_auth_unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock */
        post: operations["lock_api_v1_auth_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries */
        get: operations["entries_api_v1_entries_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_v1_entries__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_entries__entry_id__delete"];
        options?: never;
        head?: never;
        /** Edit */
        patch: operations["edit_api_v1_entries__entry_id__patch"];
        trace?: never;
    };
    "/api/v1/entries/{entry_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revisions */
        get: operations["revisions_api_v1_entries__entry_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_exports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shell */
        get: operations["shell__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Create */
        Create: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /**
             * Base Revision
             * @constant
             */
            base_revision: 0;
            payload: components["schemas"]["EntryInput"];
        };
        /** Delete */
        Delete: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Base Revision */
            base_revision: number;
        };
        /** EntryInput */
        EntryInput: {
            /**
             * Type
             * @default inbox
             * @enum {string}
             */
            type: "inbox" | "daily" | "sleep" | "creative";
            /** Raw Text */
            raw_text: string;
            /** Tags */
            tags?: string[];
            /**
             * Timezone
             * @default Europe/Warsaw
             */
            timezone: string;
            /** Occurred At Utc */
            occurred_at_utc?: string | null;
            /** Local Date */
            local_date?: string | null;
            /**
             * Time Precision
             * @default unknown
             * @enum {string}
             */
            time_precision: "instant" | "date" | "unknown";
            /** Mood Rating */
            mood_rating?: number | null;
            /** Energy Rating */
            energy_rating?: number | null;
            /** Sleep Start Utc */
            sleep_start_utc?: string | null;
            /** Wake At Utc */
            wake_at_utc?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Creative Kind */
            creative_kind?: ("idea" | "scene" | "character" | "reference" | "other") | null;
        };
        /**
         * EntryOutput
         * @description Server-managed fields shared with the generated TypeScript read contract.
         */
        EntryOutput: {
            /**
             * Type
             * @default inbox
             * @enum {string}
             */
            type: "inbox" | "daily" | "sleep" | "creative";
            /** Raw Text */
            raw_text: string;
            /** Tags */
            tags?: string[];
            /**
             * Timezone
             * @default Europe/Warsaw
             */
            timezone: string;
            /** Occurred At Utc */
            occurred_at_utc?: string | null;
            /** Local Date */
            local_date?: string | null;
            /**
             * Time Precision
             * @default unknown
             * @enum {string}
             */
            time_precision: "instant" | "date" | "unknown";
            /** Mood Rating */
            mood_rating?: number | null;
            /** Energy Rating */
            energy_rating?: number | null;
            /** Sleep Start Utc */
            sleep_start_utc?: string | null;
            /** Wake At Utc */
            wake_at_utc?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Creative Kind */
            creative_kind?: ("idea" | "scene" | "character" | "reference" | "other") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Revision */
            revision: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /**
             * Updated At Utc
             * Format: date-time
             */
            updated_at_utc: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /**
             * Privacy Class
             * @constant
             */
            privacy_class: "PRIVATE_PERSONAL";
            /**
             * Provenance Type
             * @constant
             */
            provenance_type: "USER_REPORTED";
            /** Reported Interval Seconds */
            reported_interval_seconds?: number | null;
        };
        /** EntryPage */
        EntryPage: {
            /** Items */
            items: components["schemas"]["EntryOutput"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** EntryRevisionOutput */
        EntryRevisionOutput: {
            /**
             * Type
             * @default inbox
             * @enum {string}
             */
            type: "inbox" | "daily" | "sleep" | "creative";
            /** Raw Text */
            raw_text: string;
            /** Tags */
            tags?: string[];
            /**
             * Timezone
             * @default Europe/Warsaw
             */
            timezone: string;
            /** Occurred At Utc */
            occurred_at_utc?: string | null;
            /** Local Date */
            local_date?: string | null;
            /**
             * Time Precision
             * @default unknown
             * @enum {string}
             */
            time_precision: "instant" | "date" | "unknown";
            /** Mood Rating */
            mood_rating?: number | null;
            /** Energy Rating */
            energy_rating?: number | null;
            /** Sleep Start Utc */
            sleep_start_utc?: string | null;
            /** Wake At Utc */
            wake_at_utc?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Creative Kind */
            creative_kind?: ("idea" | "scene" | "character" | "reference" | "other") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Revision */
            revision: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /**
             * Updated At Utc
             * Format: date-time
             */
            updated_at_utc: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /**
             * Privacy Class
             * @constant
             */
            privacy_class: "PRIVATE_PERSONAL";
            /**
             * Provenance Type
             * @constant
             */
            provenance_type: "USER_REPORTED";
            /** Reported Interval Seconds */
            reported_interval_seconds?: number | null;
            /** Recorded At Utc */
            recorded_at_utc?: string | null;
        };
        /** Export */
        Export: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Format
             * @enum {string}
             */
            format: "json" | "markdown";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Patch */
        Patch: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Base Revision */
            base_revision: number;
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /**
             * Confirm Type Change
             * @default false
             */
            confirm_type_change: boolean;
        };
        /** Receipt */
        Receipt: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Revision */
            revision: number;
            /**
             * Result Code
             * @enum {string}
             */
            result_code: "MAC_SAVED" | "DELETED";
        };
        /** RevisionPage */
        RevisionPage: {
            /** Items */
            items: components["schemas"]["EntryRevisionOutput"][];
            /** Next After */
            next_after: number | null;
        };
        /** Selector */
        Selector: {
            /** Ids */
            ids?: string[] | null;
            /** Types */
            types?: ("inbox" | "daily" | "sleep" | "creative")[] | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Include History
             * @default false
             */
            include_history: boolean;
        };
        /** Unlock */
        Unlock: {
            /** Code */
            code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    unlock_api_v1_auth_unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Unlock"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    lock_api_v1_auth_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    entries_api_v1_entries_get: {
        parameters: {
            query?: {
                q?: string;
                type?: string | null;
                tag?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_v1_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Delete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_v1_entries__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisions_api_v1_entries__entry_id__revisions_get: {
        parameters: {
            query?: {
                limit?: number;
                after?: number;
            };
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_exports_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Selector"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Export"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shell__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
