/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unlock */
        post: operations["unlock_api_v1_auth_unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock */
        post: operations["lock_api_v1_auth_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries */
        get: operations["entries_api_v1_entries_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: operations["get_api_v1_entries__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_v1_entries__entry_id__delete"];
        options?: never;
        head?: never;
        /** Edit */
        patch: operations["edit_api_v1_entries__entry_id__patch"];
        trace?: never;
    };
    "/api/v1/entries/{entry_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revisions */
        get: operations["revisions_api_v1_entries__entry_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_exports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_v1_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invitation */
        post: operations["invitation_api_v1_sync_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices */
        get: operations["devices_api_v1_sync_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/devices/{device_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_api_v1_sync_devices__device_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/epoch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Epoch */
        post: operations["reset_epoch_api_v1_sync_epoch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pair */
        post: operations["pair_api_v1_device_pair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize */
        post: operations["finalize_api_v1_device_finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Status */
        get: operations["ai_status_api_v1_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Mode */
        post: operations["ai_mode_api_v1_ai_mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Preview */
        post: operations["ai_preview_api_v1_ai_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/consents/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Approve */
        post: operations["ai_approve_api_v1_ai_consents__id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/consents/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Revoke */
        post: operations["ai_revoke_api_v1_ai_consents__id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Jobs */
        get: operations["ai_jobs_api_v1_ai_jobs_get"];
        put?: never;
        /** Ai Enqueue */
        post: operations["ai_enqueue_api_v1_ai_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Cancel */
        post: operations["ai_cancel_api_v1_ai_jobs__id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Memories */
        get: operations["ai_memories_api_v1_ai_memories_get"];
        put?: never;
        /** Ai Memory Create */
        post: operations["ai_memory_create_api_v1_ai_memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/memories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Memory Change */
        post: operations["ai_memory_change_api_v1_ai_memories__id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ai Suggestions */
        get: operations["ai_suggestions_api_v1_ai_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/suggestions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Suggestion Change */
        post: operations["ai_suggestion_change_api_v1_ai_suggestions__id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull */
        get: operations["pull_api_v1_device_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/device/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply */
        post: operations["apply_api_v1_device_operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shell */
        get: operations["shell__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Approval */
        Approval: {
            /** Context Hash */
            context_hash: string;
        };
        /** Create */
        Create: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /**
             * Base Revision
             * @constant
             */
            base_revision: 0;
            payload: components["schemas"]["EntryInput"];
        };
        /** Delete */
        Delete: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Base Revision */
            base_revision: number;
        };
        /** Empty */
        Empty: Record<string, never>;
        /** Enqueue */
        Enqueue: {
            /**
             * Consent Id
             * Format: uuid
             */
            consent_id: string;
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
        };
        /** EntryInput */
        EntryInput: {
            /**
             * Type
             * @default inbox
             * @enum {string}
             */
            type: "inbox" | "daily" | "sleep" | "creative";
            /** Raw Text */
            raw_text: string;
            /** Tags */
            tags?: string[];
            /**
             * Timezone
             * @default Europe/Warsaw
             */
            timezone: string;
            /** Occurred At Utc */
            occurred_at_utc?: string | null;
            /** Local Date */
            local_date?: string | null;
            /**
             * Time Precision
             * @default unknown
             * @enum {string}
             */
            time_precision: "instant" | "date" | "unknown";
            /** Mood Rating */
            mood_rating?: number | null;
            /** Energy Rating */
            energy_rating?: number | null;
            /** Sleep Start Utc */
            sleep_start_utc?: string | null;
            /** Wake At Utc */
            wake_at_utc?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Creative Kind */
            creative_kind?: ("idea" | "scene" | "character" | "reference" | "other") | null;
        };
        /**
         * EntryOutput
         * @description Server-managed fields shared with the generated TypeScript read contract.
         */
        EntryOutput: {
            /**
             * Type
             * @default inbox
             * @enum {string}
             */
            type: "inbox" | "daily" | "sleep" | "creative";
            /** Raw Text */
            raw_text: string;
            /** Tags */
            tags?: string[];
            /**
             * Timezone
             * @default Europe/Warsaw
             */
            timezone: string;
            /** Occurred At Utc */
            occurred_at_utc?: string | null;
            /** Local Date */
            local_date?: string | null;
            /**
             * Time Precision
             * @default unknown
             * @enum {string}
             */
            time_precision: "instant" | "date" | "unknown";
            /** Mood Rating */
            mood_rating?: number | null;
            /** Energy Rating */
            energy_rating?: number | null;
            /** Sleep Start Utc */
            sleep_start_utc?: string | null;
            /** Wake At Utc */
            wake_at_utc?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Creative Kind */
            creative_kind?: ("idea" | "scene" | "character" | "reference" | "other") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Revision */
            revision: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /**
             * Updated At Utc
             * Format: date-time
             */
            updated_at_utc: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 2;
            /**
             * Privacy Class
             * @constant
             */
            privacy_class: "PRIVATE_PERSONAL";
            /**
             * Provenance Type
             * @constant
             */
            provenance_type: "USER_REPORTED";
            /** Reported Interval Seconds */
            reported_interval_seconds?: number | null;
        };
        /** EntryPage */
        EntryPage: {
            /** Items */
            items: components["schemas"]["EntryOutput"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** EntryRevisionOutput */
        EntryRevisionOutput: {
            /**
             * Type
             * @default inbox
             * @enum {string}
             */
            type: "inbox" | "daily" | "sleep" | "creative";
            /** Raw Text */
            raw_text: string;
            /** Tags */
            tags?: string[];
            /**
             * Timezone
             * @default Europe/Warsaw
             */
            timezone: string;
            /** Occurred At Utc */
            occurred_at_utc?: string | null;
            /** Local Date */
            local_date?: string | null;
            /**
             * Time Precision
             * @default unknown
             * @enum {string}
             */
            time_precision: "instant" | "date" | "unknown";
            /** Mood Rating */
            mood_rating?: number | null;
            /** Energy Rating */
            energy_rating?: number | null;
            /** Sleep Start Utc */
            sleep_start_utc?: string | null;
            /** Wake At Utc */
            wake_at_utc?: string | null;
            /** Sleep Quality */
            sleep_quality?: number | null;
            /** Creative Kind */
            creative_kind?: ("idea" | "scene" | "character" | "reference" | "other") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Revision */
            revision: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /**
             * Updated At Utc
             * Format: date-time
             */
            updated_at_utc: string;
            /**
             * Schema Version
             * @enum {integer}
             */
            schema_version: 1 | 2;
            /**
             * Privacy Class
             * @constant
             */
            privacy_class: "PRIVATE_PERSONAL";
            /**
             * Provenance Type
             * @constant
             */
            provenance_type: "USER_REPORTED";
            /** Reported Interval Seconds */
            reported_interval_seconds?: number | null;
            /** Recorded At Utc */
            recorded_at_utc?: string | null;
        };
        /** EpochReset */
        EpochReset: {
            /**
             * Prune Tombstones
             * @default false
             */
            prune_tombstones: boolean;
        };
        /** Export */
        Export: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Format
             * @enum {string}
             */
            format: "json" | "markdown";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MemoryChange */
        MemoryChange: {
            /** Revision */
            revision: number;
            /**
             * Action
             * @enum {string}
             */
            action: "confirm" | "edit" | "reject" | "delete";
            /** Content */
            content?: string | null;
        };
        /** MemoryCreate */
        MemoryCreate: {
            /**
             * Scope
             * @default preferences
             * @enum {string}
             */
            scope: "preferences" | "organization";
            /** Content */
            content: string;
            /** Expires At */
            expires_at?: number | null;
        };
        /** Packet */
        Packet: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /** Base Revision */
            base_revision: number;
            /**
             * Operation Type
             * @enum {string}
             */
            operation_type: "create" | "edit" | "delete";
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /**
             * Timezone
             * @default Europe/Warsaw
             */
            timezone: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 2;
            /** Local Sequence */
            local_sequence: number;
            payload?: components["schemas"]["EntryInput"] | null;
            /**
             * Confirm Type Change
             * @default false
             */
            confirm_type_change: boolean;
        };
        /** Pair */
        Pair: {
            /** Invitation */
            invitation: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Label */
            label: string;
        };
        /** Patch */
        Patch: {
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Base Revision */
            base_revision: number;
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /**
             * Confirm Type Change
             * @default false
             */
            confirm_type_change: boolean;
        };
        /** PreviewRequest */
        PreviewRequest: {
            /**
             * Task
             * @enum {string}
             */
            task: "capture_classify" | "organize_selected" | "memory_propose";
            /**
             * Provider
             * @default mock
             * @enum {string}
             */
            provider: "mock" | "codex-disabled";
            /** Entries */
            entries: components["schemas"]["Ref"][];
            /** Memories */
            memories?: components["schemas"]["Ref"][];
        };
        /** Receipt */
        Receipt: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /**
             * Operation Id
             * Format: uuid
             */
            operation_id: string;
            /** Revision */
            revision: number;
            /**
             * Result Code
             * @enum {string}
             */
            result_code: "MAC_SAVED" | "DELETED";
        };
        /** Ref */
        Ref: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision */
            revision: number;
        };
        /** RevisionPage */
        RevisionPage: {
            /** Items */
            items: components["schemas"]["EntryRevisionOutput"][];
            /** Next After */
            next_after: number | null;
        };
        /** RuntimeMode */
        RuntimeMode: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "OFF" | "MOCK";
        };
        /** Selector */
        Selector: {
            /** Ids */
            ids?: string[] | null;
            /** Types */
            types?: ("inbox" | "daily" | "sleep" | "creative")[] | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /**
             * Include History
             * @default false
             */
            include_history: boolean;
        };
        /** SuggestionChange */
        SuggestionChange: {
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "edit" | "reject" | "ignore" | "undo";
            /** Type */
            type?: ("inbox" | "daily" | "sleep" | "creative") | null;
            /** Tags */
            tags?: ("нотатка" | "ідея" | "план" | "щоденник")[] | null;
            /**
             * Confirm Type Change
             * @default false
             */
            confirm_type_change: boolean;
        };
        /** Unlock */
        Unlock: {
            /** Code */
            code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    unlock_api_v1_auth_unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Unlock"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    lock_api_v1_auth_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    entries_api_v1_entries_get: {
        parameters: {
            query?: {
                q?: string;
                type?: string | null;
                tag?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_api_v1_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_v1_entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Delete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_api_v1_entries__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revisions_api_v1_entries__entry_id__revisions_get: {
        parameters: {
            query?: {
                limit?: number;
                after?: number;
            };
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_exports_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Selector"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_v1_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Export"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invitation_api_v1_sync_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpochReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    devices_api_v1_sync_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    revoke_api_v1_sync_devices__device_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpochReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_epoch_api_v1_sync_epoch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpochReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pair_api_v1_device_pair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Pair"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_api_v1_device_finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_status_api_v1_ai_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ai_mode_api_v1_ai_mode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeMode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_preview_api_v1_ai_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_approve_api_v1_ai_consents__id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Approval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_revoke_api_v1_ai_consents__id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_jobs_api_v1_ai_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ai_enqueue_api_v1_ai_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Enqueue"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_cancel_api_v1_ai_jobs__id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_memories_api_v1_ai_memories_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_memory_create_api_v1_ai_memories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_memory_change_api_v1_ai_memories__id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_suggestions_api_v1_ai_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ai_suggestion_change_api_v1_ai_suggestions__id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_api_v1_device_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    apply_api_v1_device_operations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Packet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shell__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
