import {readFileSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../apps/web/package.json',import.meta.url));
const Ajv=require('ajv/dist/2020');const formats=require('ajv-formats');const standalone=require('ajv/dist/standalone').default;
const spec=JSON.parse(readFileSync(new URL('../packages/contracts/openapi.json',import.meta.url),'utf8'));
const schema=structuredClone(spec.components.schemas.EntryInput);
const ajv=new Ajv({code:{source:true,esm:true},strict:false,allErrors:true});formats(ajv);
const validate=ajv.compile(schema);
let code=standalone(ajv,validate);
const imports=[];
code=code.replace(/const (\w+) = require\("([^"]+)"\)([^;]+);/g,(whole,name,module,suffix)=>{const base=name+'Import';imports.push(`import ${base} from '${module}';`);return suffix==='.default'?`const ${name}=${base}.default || ${base};`:`const ${name}=${base}${suffix};`;});
writeFileSync(new URL('../apps/web/src/entry-schema-validator.js',import.meta.url),imports.join('\n')+'\n'+code);
writeFileSync(new URL('../apps/web/src/entry-schema-validator.d.ts',import.meta.url),'export default function validate(data: unknown): boolean;\n');
